# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list = channel.unary_stream(
                '/ChatService/list',
                request_serializer=chat__pb2.ClientChannelAction.SerializeToString,
                response_deserializer=chat__pb2.ServerChannelActionMessage.FromString,
                )
        self.join = channel.unary_stream(
                '/ChatService/join',
                request_serializer=chat__pb2.ClientChannelAction.SerializeToString,
                response_deserializer=chat__pb2.ServerChannelActionMessage.FromString,
                )
        self.leave = channel.unary_stream(
                '/ChatService/leave',
                request_serializer=chat__pb2.ClientChannelAction.SerializeToString,
                response_deserializer=chat__pb2.ServerChannelActionMessage.FromString,
                )
        self.post = channel.unary_stream(
                '/ChatService/post',
                request_serializer=chat__pb2.ClientPostMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerChannelActionMessage.FromString,
                )
        self.help = channel.unary_stream(
                '/ChatService/help',
                request_serializer=chat__pb2.ClientChannelAction.SerializeToString,
                response_deserializer=chat__pb2.ServerChannelActionMessage.FromString,
                )
        self.receive = channel.unary_stream(
                '/ChatService/receive',
                request_serializer=chat__pb2.ClientChannelAction.SerializeToString,
                response_deserializer=chat__pb2.ServerChannelActionMessage.FromString,
                )


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def leave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def help(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def receive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list': grpc.unary_stream_rpc_method_handler(
                    servicer.list,
                    request_deserializer=chat__pb2.ClientChannelAction.FromString,
                    response_serializer=chat__pb2.ServerChannelActionMessage.SerializeToString,
            ),
            'join': grpc.unary_stream_rpc_method_handler(
                    servicer.join,
                    request_deserializer=chat__pb2.ClientChannelAction.FromString,
                    response_serializer=chat__pb2.ServerChannelActionMessage.SerializeToString,
            ),
            'leave': grpc.unary_stream_rpc_method_handler(
                    servicer.leave,
                    request_deserializer=chat__pb2.ClientChannelAction.FromString,
                    response_serializer=chat__pb2.ServerChannelActionMessage.SerializeToString,
            ),
            'post': grpc.unary_stream_rpc_method_handler(
                    servicer.post,
                    request_deserializer=chat__pb2.ClientPostMessage.FromString,
                    response_serializer=chat__pb2.ServerChannelActionMessage.SerializeToString,
            ),
            'help': grpc.unary_stream_rpc_method_handler(
                    servicer.help,
                    request_deserializer=chat__pb2.ClientChannelAction.FromString,
                    response_serializer=chat__pb2.ServerChannelActionMessage.SerializeToString,
            ),
            'receive': grpc.unary_stream_rpc_method_handler(
                    servicer.receive,
                    request_deserializer=chat__pb2.ClientChannelAction.FromString,
                    response_serializer=chat__pb2.ServerChannelActionMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatService/list',
            chat__pb2.ClientChannelAction.SerializeToString,
            chat__pb2.ServerChannelActionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatService/join',
            chat__pb2.ClientChannelAction.SerializeToString,
            chat__pb2.ServerChannelActionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def leave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatService/leave',
            chat__pb2.ClientChannelAction.SerializeToString,
            chat__pb2.ServerChannelActionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatService/post',
            chat__pb2.ClientPostMessage.SerializeToString,
            chat__pb2.ServerChannelActionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def help(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatService/help',
            chat__pb2.ClientChannelAction.SerializeToString,
            chat__pb2.ServerChannelActionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def receive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChatService/receive',
            chat__pb2.ClientChannelAction.SerializeToString,
            chat__pb2.ServerChannelActionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
