# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\">\n\x0e\x43hannelMembers\x12\x13\n\x0b\x43hannelName\x18\x01 \x01(\t\x12\x17\n\x0fnumberOfClients\x18\x02 \x01(\t\"N\n\x13\x43lientChannelAction\x12\x10\n\x08nickName\x18\x01 \x01(\t\x12\x13\n\x0b\x63hannelName\x18\x02 \x01(\t\x12\x10\n\x08\x63lientId\x18\x03 \x01(\t\"-\n\x1aServerChannelActionMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"]\n\x11\x43lientPostMessage\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x10\n\x08nickName\x18\x02 \x01(\t\x12\x13\n\x0b\x63hannelName\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t2\xfd\x02\n\x0b\x43hatService\x12;\n\x04list\x12\x14.ClientChannelAction\x1a\x1b.ServerChannelActionMessage0\x01\x12;\n\x04join\x12\x14.ClientChannelAction\x1a\x1b.ServerChannelActionMessage0\x01\x12<\n\x05leave\x12\x14.ClientChannelAction\x1a\x1b.ServerChannelActionMessage0\x01\x12\x39\n\x04post\x12\x12.ClientPostMessage\x1a\x1b.ServerChannelActionMessage0\x01\x12;\n\x04help\x12\x14.ClientChannelAction\x1a\x1b.ServerChannelActionMessage0\x01\x12>\n\x07receive\x12\x14.ClientChannelAction\x1a\x1b.ServerChannelActionMessage0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELMEMBERS._serialized_start=76
  _CHANNELMEMBERS._serialized_end=138
  _CLIENTCHANNELACTION._serialized_start=140
  _CLIENTCHANNELACTION._serialized_end=218
  _SERVERCHANNELACTIONMESSAGE._serialized_start=220
  _SERVERCHANNELACTIONMESSAGE._serialized_end=265
  _CLIENTPOSTMESSAGE._serialized_start=267
  _CLIENTPOSTMESSAGE._serialized_end=360
  _CHATSERVICE._serialized_start=363
  _CHATSERVICE._serialized_end=744
# @@protoc_insertion_point(module_scope)
